MonitoringStations.WebUI/Controllers/RoleController.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MonitoringStations.WebUI.Models;

namespace MonitoringStations.WebUI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUserCustom> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUserCustom> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public ViewResult Index()
        {
            return View(_roleManager.Roles.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Required] string name)
        {
            if (ModelState.IsValid)
            {
                var result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                    return RedirectToAction("Index");
                Errors(result);
            }

            return View(name);
        }

        public async Task<IActionResult> Update(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            var members = new List<IdentityUserCustom>();
            var nonMembers = new List<IdentityUserCustom>();

            var users = _userManager.Users.ToList();
            foreach (var it in users)
                if (await _userManager.IsInRoleAsync(it, role.Name))
                    members.Add(it);
                else
                    nonMembers.Add(it);

            var result = new RoleEdit
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            };

            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Update(RoleModification roleModify)
        {
            IdentityResult result;
            IdentityUserCustom user;

            if (ModelState.IsValid)
            {
                foreach (var it in roleModify.AddIds ?? new string[] { })
                {
                    user = await _userManager.FindByIdAsync(it);

                    if (user != null)
                    {
                        result = await _userManager.AddToRoleAsync(user, roleModify.RoleName);
                        if (!result.Succeeded)
                            Errors(result);
                    }
                }

                foreach (var it in roleModify.DeleteIds ?? new string[] { })
                {
                    user = await _userManager.FindByIdAsync(it);

                    if (user != null)
                    {
                        result = await _userManager.RemoveFromRoleAsync(user, roleModify.RoleName);
                        if (!result.Succeeded)
                            Errors(result);
                    }
                }

                return await Update(roleModify.RoleId);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                Errors(result);
            }
            else
            {
                ModelState.AddModelError("", "No role found");
            }

            return View("Index", _roleManager.Roles);
        }

        private void Errors(IdentityResult result)
        {
            foreach (var error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }
    }
}

MonitoringStations.WebUI/Controllers/StationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using MonitoringStations.Core.Interfaces;
using MonitoringStations.Core.ViewModels;

namespace MonitoringStations.WebUI.Controllers
{
    [Authorize(Roles = "Support, Admin")]
    public class StationController : Controller
    {
        private readonly IStationService _stationService;

        public StationController(IStationService service)
        {
            _stationService = service;
        }

        public IActionResult Index()
        {
            var model = _stationService.GetStations();

            var viewModel = new StationViewModel
            {
                Stations = model.Result
            };
            
            return View(viewModel);
        }
    }
}

MonitoringStations.WebUI/Controllers/UserController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using MonitoringStations.WebUI.Models;
using Microsoft.AspNetCore.Authorization;

namespace MonitoringStations.WebUI.Controllers
{

    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUserCustom> _userManager;

        public UserController(UserManager<IdentityUserCustom> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View(_userManager.Users.OrderBy(x=>x.UserName).ToList());
        }
    }
}

MonitoringStations.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MonitoringStations</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/all.min.css" />
    <link rel="stylesheet" href="~/css/mvc-grid/mvc-grid.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/di_support_logo-small.png" width="60" height="60" alt="Monitoring Stations - DI-SUPPORT" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Station" asp-action="Index">Stations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Add User</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Monitoring Stations <b>DI-SUPPORT</b>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/all.min.js"></script>
    <script src="~/js/mvc-grid/mvc-grid.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        document.querySelectorAll(".mvc-grid").forEach(element => new MvcGrid(element));
    </script>
    @RenderSection("Scripts", false)
</body>
</html>